{{- if .Values.ingress.enabled -}}
# VirtualService for Istio Gateway (tfy-wildcard)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "spark-job-fallback-management.fullname" . }}
  labels:
    {{- include "spark-job-fallback-management.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.ingress.gateway }}
  hosts:
    - {{ .Values.ingress.host | quote }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.ingress.path | default "/" }}
      route:
        - destination:
            host: {{ include "spark-job-fallback-management.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
{{- end }}
